export const config = {
  name: {
    id: 'name',
    name: 'name',
    label: 'Name of the product',
    value: '',
    error: false,
    helperText: '',
    metric: '',
    required: true,
  },
  calories: {
    id: 'calories',
    name: 'calories',
    label: 'Calories',
    value: '',
    error: false,
    helperText: '',
    metric: '',
    required: true,
  },
  fat: {
    id: 'fat',
    name: 'fat',
    label: 'Fat',
    value: '',
    error: false,
    helperText: '',
    metric: 'g',
    required: true,
  },
  carbs: {
    id: 'carbs',
    name: 'carbs',
    label: 'Carbs',
    value: '',
    error: false,
    helperText: '',
    metric: 'g',
    required: true,
  },
  protein: {
    id: 'protein',
    name: 'protein',
    label: 'Protein',
    value: '',
    error: false,
    helperText: '',
    metric: 'g',
    required: true,
  },
};
